# 应用配置
app:
  name: SupCaller
  env: development
  port: 8080
  secret_key: supcaller_secret_key
  
ignore:
  - /api/v1/auth/login

# 数据库配置
database:
  host: localhost
  port: 3306
  username: root
  password: wm123
  dbname: supcaller
  charset: utf8mb4
  parseTime: True
  loc: Local

# JWT配置
jwt:
  secret: supcaller_jwt_secret
  expire: 24h

# 日志配置
log:
  level: info
  format: json
  output: file